version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    networks:
      - network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  migrate:
    image: migrate/migrate
    networks:
      - network
    volumes:
      - ./migrations:/migrations
    command: -path /migrations -database ${POSTGRESQL_URL} up 3 
    links: 
      - db
    depends_on:
      db:
        condition: service_healthy
  
  app:
    container_name: app
    build: ./app
    image: my_node_api
    networks:
      - network
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DB_HOST: ${DB_HOST}
    command: node app/dist/app.js

networks:
  network:
    name: network
    driver: bridge

